name: Semgrep Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and install Semgrep + jq
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
          sudo apt-get update && sudo apt-get install -y jq
      - name: Run Semgrep and save results
        run: |
          semgrep --config=p/default --json --output=semgrep-results.json .
        continue-on-error: true  # <-- This prevents the job from failing if findings are found

      - name: Convert JSON to CSV
        run: |
          jq -r '
            ["check_id", "path", "line", "message"],
            (.results[] | [.check_id, .path, .start.line, .extra.message])
          | @csv' semgrep-results.json > semgrep-results.csv

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results-csv
          path: semgrep-results.csv
