name: Semgrep Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep and save results
        run: |
          semgrep --config=p/default --json --output=semgrep-results.json .
        continue-on-error: true  # <-- This prevents the job from failing if findings are found

      - name: Upload Semgrep results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json
